version = 1
SPDX-PackageName = "SRFI 104"
SPDX-PackageSupplier = "Arthur A. Gleckler <srfi-editors@srfi.schemers.org>"
SPDX-PackageDownloadLocation = "https://github.com/scheme-requests-for-implementation/srfi-104"
annotations = []
